version: '3.8'
services:
  myRabbit:
    ports:
     - '5672:5672'
    image: rabbitmq:3.8.1-management
    environment:
      - RABBITMQ_DEFALUT_USER=admin
      - RABBITMQ_DEFALUT_PASS=admin
      - RABBITMQ_DEFALUT_VHOST=myvhost
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
  mongo_db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
  postgres_db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  consumer:
    build: ./consumer
    ports:
      - '81:80'
    environment:
      - MONGO_URI=monodb://mongo_db:27017/test
      - EXPRESS_PORT=80
      - RABBIT_URI=amqp://admin:admin@myRabbit:5672/myvhost
    depends_on:
      - myRabbit
      - mongo_db
  procuder:
    restart: on-failure
    build: ./procuder
    ports:
      - '80:80'
    environment:
      - PG_URI=postgres://postgres:postgres@postgres_db:5432/postgres
      - EXPRESS_PORT=80
      - RABBIT_URI=amqp://admin:admin@myRabbit:5672/myvhost
    depends_on:
      - myRabbit
      - postgres_db
    